# Generated by Django 5.2.8 on 2025-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("title", models.CharField(max_length=250, verbose_name="title")),
                (
                    "brand",
                    models.CharField(
                        default="un-branded", max_length=250, verbose_name="brand"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("slug", models.SlugField(max_length=255, verbose_name="slug")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="price"
                    ),
                ),
                ("image", models.ImageField(upload_to="images/", verbose_name="image")),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="published"),
                ),
            ],
            options={
                "verbose_name_plural": "products",
            },
        ),
    ]
