# Generated by Django 5.2.8 on 2025-11-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_category_alter_product_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"], "verbose_name_plural": "products"},
        ),
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="featured"),
        ),
    ]
