# Generated by Django 5.2.8 on 2025-11-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_size_product_available_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="available_sizes",
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_size",
                to="store.size",
                verbose_name="size",
            ),
        ),
    ]
